manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Amos698
      #url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      #revision: main
      revision: feature-test
      import: app/west.yml
  self:
    path: config